version: '3'
services:
  project-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
  
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=lloyd
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
    